#! /usr/bin/env python

# The MIT License
# 
# Copyright (c) 2011 Timothy N. Tsvetkov <timothy.tsvetkov@gmail.com>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import sys
import os
import re

def generate(migration_name):
	 for r in os.popen("./script/generate migration %s" % (migration_name)):
	 	print r
	 	match = re.match(r'\s*create (?P<file_name>.*)', r)
	 	if match is not None and match.group('file_name') is not None:
	 		os.popen('mate %s' % (match.group('file_name')))

if __name__ == "__main__":
	if len(sys.argv) < 2:
		print "Plese type migration name"
		exit(0)
	
	generate(sys.argv[1])

